# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8d024eed04bf28b4a8b172e2ff11828950ec17c367ccad65d062ad3ee6cd41c0a53a1adea0e44f4c3bee0985d04b396912da8a3223203fc85e2b3188b3553d1b

test:
  secret_key_base: 0b7c29434574163bd98c386539ce22aa75b0af04423b3f85aa5d6d8a193c849eaeeb41fc9aa235486ae54fd865907b6e9b93ec5f7b43bba25cfc73cc20e25ba9

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
